services:
  - type: web
    name: sistema-orcamento
    env: python
    buildCommand: ""
    startCommand: gunicorn sistema.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sistema.settings
      - key: PYTHON_VERSION
        value: 3.11
