# Generated by Django 5.2.3 on 2025-07-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracoesSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensal_desejado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_por_semana', models.PositiveIntegerField()),
                ('horas_por_dia', models.PositiveIntegerField()),
                ('margem_lucro_padrao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentual_energia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentual_internet', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('custo_impressao_pb', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('custo_impressao_colorida', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=150)),
                ('razao_social', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_pacote', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_por_pacote', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade', models.PositiveIntegerField()),
                ('tempo_por_unidade', models.PositiveIntegerField(help_text='Tempo por unidade (em minutos)')),
                ('margem_lucro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('folhas_pb', models.PositiveIntegerField(default=0)),
                ('folhas_coloridas', models.PositiveIntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaisUtilizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiaisutilizados', to='core.orcamento')),
            ],
        ),
    ]
