# Generated by Django 5.2.3 on 2025-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='configuracoessistema',
            name='custo_impressao_colorida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Custo impressão colorida'),
        ),
        migrations.AlterField(
            model_name='configuracoessistema',
            name='custo_impressao_pb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Custo impressão PB'),
        ),
        migrations.AlterField(
            model_name='configuracoessistema',
            name='dias_por_semana',
            field=models.PositiveIntegerField(verbose_name='Dias por semana'),
        ),
        migrations.AlterField(
            model_name='configuracoessistema',
            name='horas_por_dia',
            field=models.PositiveIntegerField(verbose_name='Horas por dia'),
        ),
        migrations.AlterField(
            model_name='configuracoessistema',
            name='margem_lucro_padrao',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Margem de lucro padrão (%)'),
        ),
        migrations.AlterField(
            model_name='configuracoessistema',
            name='percentual_energia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Energia (%)'),
        ),
        migrations.AlterField(
            model_name='configuracoessistema',
            name='percentual_internet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Internet (%)'),
        ),
        migrations.AlterField(
            model_name='configuracoessistema',
            name='valor_mensal_desejado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor mensal desejado'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logotipo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(max_length=150, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=150, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='materiaisutilizados',
            name='quantidade_utilizada',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade utilizada'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='preco_pacote',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço por pacote'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantidade_por_pacote',
            field=models.PositiveIntegerField(verbose_name='Quantidade por pacote'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='folhas_coloridas',
            field=models.PositiveIntegerField(default=0, verbose_name='Folhas coloridas'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='folhas_pb',
            field=models.PositiveIntegerField(default=0, verbose_name='Folhas PB'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='margem_lucro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Margem de lucro (%)'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do orçamento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='tempo_por_unidade',
            field=models.PositiveIntegerField(verbose_name='Tempo por unidade (minutos)'),
        ),
    ]
