# Generated by Django 5.2 on 2025-07-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orcamento_materiais_cliente_fornece'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unidade',
            field=models.CharField(default='un', max_length=20, verbose_name='Unidade'),
        ),
    ]
