# Generated by Django 5.2 on 2025-07-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_material_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaisutilizados',
            name='fornecido_pelo_cliente',
            field=models.BooleanField(default=False, verbose_name='Fornecido pelo cliente?'),
        ),
    ]
