# Generated by Django 5.2 on 2025-07-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_materiaisutilizados_fornecido_pelo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='materiais_cliente_fornece',
        ),
    ]
