# Generated by Django 5.2.3 on 2025-07-23 15:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_orcamento_materiais_cliente_fornece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logotipo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logotipo'),
        ),
    ]
