# Generated by Django 5.2.3 on 2025-07-23 23:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_empresa_logotipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoessistema',
            name='dias_por_semana',
            field=models.PositiveIntegerField(default=5, verbose_name='Dias por semana'),
        ),
        migrations.AlterField(
            model_name='configuracoessistema',
            name='horas_por_dia',
            field=models.PositiveIntegerField(default=8, verbose_name='Horas por dia'),
        ),
        migrations.AlterField(
            model_name='configuracoessistema',
            name='margem_lucro_padrao',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Margem de lucro padrão (%)'),
        ),
        migrations.AlterField(
            model_name='configuracoessistema',
            name='valor_mensal_desejado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor mensal desejado'),
        ),
    ]
